### ISSUE TITLE
Posso mettere una serie di Views in formato Xib da far scorrere?

### ISSUE THREAD

**Issue by AndrexOfficial** [malcommac/DMLazyScrollView#1]
Se è possibile fare cioò mi potresti dire come implementarlo tramite codice?
Grazie mille

**Comment by malcommac** [comment]
Per caricare un UIView contenuto in uno xib dovresti fare una cosa del genere:

  NSArray *viewsInXib =  [[NSBundle mainBundle] loadNibNamed:@"tuoXIB" owner:self options:nil];
   UIView *ourView = [viewsInXib objectAtIndex:0];
